name: sim2real
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - cfgrib=0.9.10.4
  - ipykernel=6.25.2
  - ipython=8.15.0
  - jedi=0.19.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - pip=23.2.1
  - python=3.11.5
  - setuptools=68.1.2
  - wheel=0.41.2
  - pip:
      - algebra==1.2.1
      - appdirs==1.4.4
      - attrs==23.1.0
      - backends==1.5.4
      - backends-matrix==1.3.0
      - beartype==0.15.0
      - cartopy==0.22.0
      - certifi==2023.7.22
      - cftime==1.6.2
      - charset-normalizer==3.2.0
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==2.2.1
      - contourpy==1.1.0
      - cycler==0.11.0
      - dask==2023.8.1
      - deepsensor==0.3.6
      - distributed==2023.8.1
      - docker-pycreds==0.4.0
      - fdm==0.4.1
      - filelock==3.12.2
      - fiona==1.9.4.post1
      - fonttools==4.42.1
      - fsspec==2023.6.0
      - geopandas==0.13.2
      - gitdb==4.0.10
      - gitpython==3.1.32
      - idna==3.4
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - locket==1.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mlkernels==0.4.0
      - mpmath==1.3.0
      - msgpack==1.0.5
      - netcdf4==1.6.4
      - networkx==3.1
      - neuralprocesses==0.2.2
      - numpy==1.25.2
      - opt-einsum==3.3.0
      - pandas==2.0.3
      - partd==1.4.0
      - pathtools==0.1.2
      - pillow==10.0.0
      - plum-dispatch==2.2.0
      - pooch==1.7.0
      - protobuf==4.24.2
      - pyarrow==13.0.0
      - pyparsing==3.0.9
      - pyproj==3.6.0
      - pyshp==2.3.1
      - python-slugify==8.0.1
      - pytz==2023.3
      - pyyaml==6.0.1
      - requests==2.31.0
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - shapely==2.0.1
      - smmap==5.0.0
      - sortedcontainers==2.4.0
      - stheno==1.4.1
      - sympy==1.12
      - tblib==2.0.0
      - text-unidecode==1.3
      - threadpoolctl==3.2.0
      - toolz==0.12.0
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - tqdm==4.66.1
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==2.0.4
      - varz==0.8.1
      - wandb==0.15.8
      - wbml==0.4.1
      - xarray==2023.8.0
      - zict==3.0.0
      - rioxarray==0.15.1
